# Generated by Django 3.0.2 on 2020-11-26 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statemachine', '0002_auto_20201124_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='statemachine.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='statemachine.State'),
        ),
        migrations.CreateModel(
            name='StateNextStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_order', models.PositiveIntegerField(default=0)),
                ('next_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_state', to='statemachine.State')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_id', to='statemachine.State')),
            ],
            options={
                'ordering': ('priority_order',),
            },
        ),
        migrations.AddField(
            model_name='state',
            name='next_states',
            field=models.ManyToManyField(through='statemachine.StateNextStates', to='statemachine.State'),
        ),
    ]
