# Generated by Django 3.0.2 on 2020-12-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statemachine', '0004_userstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='pre_state_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
