# Generated by Django 3.0.2 on 2020-12-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statemachine', '0005_userstate_pre_state_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='option_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
