# Generated by Django 3.0.2 on 2020-12-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statemachine', '0007_state_terminal_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'radio'), (2, 'multiselect'), (3, 'informational')], db_column='type', default=1),
        ),
    ]
